<?php

/**
 * MensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensaje');
    }

     

     public function getMensajesPorEmisorYReceptor($emisor, $receptor){
         $query = Doctrine_Core::getTable('mensaje')
         ->createQuery('mensaje')
         ->where("mensaje.emisor = $emisor")->andWhere("mensaje.receptor = $receptor")
         ->orWhere("mensaje.emisor = $receptor")->andWhere("mensaje.receptor = $emisor")
         ->execute();
         return $query;
    }
}
